disabled_rules:
    - trailing_whitespace
    - identifier_name
    - multiple_closures_with_trailing_closure
    - nesting
    - type_body_length
    - function_body_length
    - type_name
    - generic_type_name
    - cyclomatic_complexity
    - large_tuple
    - private_over_fileprivate
    - file_length
    - function_parameter_count
excluded:
    - Pods
